CREATE OR REPLACE TEMP TABLE CAT_APPROVED_DURATIONS AS
SELECT COLUMN1::VARCHAR AS PRODUCT_DESCRIPTION,
       COLUMN2::NUMBER AS DURATION_MONTHS,
       COLUMN3::NUMBER AS DURATION_DAYS
FROM VALUES
  ('Mighty Monthly Pass', 1, NULL),
  ('10 Machine Classes', 6, NULL),
  ('1 Machine Class', 6, NULL),
  ('20 Machine Classes - BEST DEAL', 6, NULL),
  ('3 Machine Classes', 6, NULL),
  ('20 Machine Classes', 6, NULL),
  ('New Client Special: 5 for $99 (valid for 1 month)', 1, NULL),
  ('Series of 10 Private Appointments', 6, NULL),
  ('New Client Special 5 Classes for $99 (valid for 1 month)', 1, NULL),
  ('Student Mighty Monthly Pass', 1, NULL),
  ('Mighty Monthly 12 Pass', 1, NULL),
  ('Series of 5 Private Appointments', 6, NULL),
  ('Founding Members MMP', 1, NULL),
  ('Ready, Set, Spring! 8 Classes for $280 (Limit 3, Valid in RH, PH, and Marin Only)', 6, NULL),
  ('Ocean Park Founder’s 50 Mighty Monthly Pass', 1, NULL),
  ('Mighty Monthly 8 Pass', 1, NULL),
  ('Single Private Appointment', 6, NULL),
  ('Welcome Back Offer: 5 classes for $99 (valid for 2 months)', 2, NULL),
  ('New Private Client Special - 3 sessions *First Timers Only*', 2, NULL),
  ('Bloom In Strength Flash Sale - 8 classes for $280', 6, NULL),
  ('New Client Special: 5 Classes for $99- Valid for 1 month', 1, NULL),
  ('20 Machine Classes - Best Deal!', 6, NULL),
  ('Russian Hill Founders MMP', 1, NULL),
  ('Tinsel & Tone Flash Sale - 8 classes for $249 (LA only)', 6, NULL),
  ('Align & Shine Summer Flash Sale - 8 classes for $249 (limit 3, valid in LA region only)', 6, NULL),
  ('Final Payment - PTT', NULL, 1),
  ('Core & Cupid Flash Sale - 8 classes for $280 (East Bay only)', 6, NULL),
  ('Spooky Strength Flash Sale - 6 Classes for $218 (Limit 3, SF Region Only)', 6, NULL),
  ('Ready Set Spring - 8 classes for $240 (SM/WW only, limit 3)', 6, NULL),
  ('Align & Shine Summer Flash Sale - 8 classes for $280 (limit 3, valid in SF region only)', 6, NULL),
  ('Ready, Set, Spring! 8 Classes for $240 (Limit 3, Valid in Lafayette/Berkeley Only)', 6, NULL),
  ('Core & Cupid Flash Sale - 8 classes for $295 (SF only)', 6, NULL),
  ('Series of 20 Private Appointments', 6, NULL),
  ('Mighty Monthly 15 Pass', 1, NULL),
  ('Dynamic Pricing', 12, NULL),
  ('6 Machine Classes', 6, NULL),
  ('Align & Shine Summer Flash Sale - 8 classes for $249 (limit 3, valid in East Bay region only)', 6, NULL),
  ('New Private Client Special: 3 Privates for $225', 2, NULL),
  ('1st Payment - PTT', NULL, 1),
  ('Mighty Monthly 20 Pass', 1, NULL),  -- 2026-07-08 correction per user: 1 month, not 1 day
  ('Danville Founder’s 50 Mighty Monthly Pass', 1, NULL),
  ('Core & Cupid Flash Sale - 8 classes for $295 (SF/Marin only)', 6, NULL),
  ('Spooky Strength Flash Sale - 6 Classes for $199 (Limit 3, Valid in East Bay Region Only)', 6, NULL),
  ('Mini Mighty Monthly Pass', 1, NULL),
  ('Pre-Opening Russian Hill MMP', 1, NULL),
  ('1st  Payment - PTT', NULL, 1),
  ('Deposit', NULL, 1),
  ('Next Stop: Russian Hill! - 3 classes for $73', 1, NULL),
  ('Full Single Payment - PTT', NULL, 1),
  ('Master Instructor - Series of 10 Privates', 6, NULL),
  ('Mighty Monthly 8 Privates Pass', 1, NULL),
  ('ClassPass Special: 4 for $75', 2, NULL),
  ('New Private Client Special - 3 Sessions *First Timers Only*', 2, NULL),
  ('Next Stop: Ocean Park! - 3 Classes for $73', 1, NULL),
  ('Series of 10 Semi-Private Appointments', 6, NULL),
  ('PTT 1st payment', NULL, 1),
  ('PTT Final Payment', NULL, 1),
  ('Series of 20 Semi Private Appointments', 6, NULL),
  ('Master Instructor - Series of 5 Privates', 6, NULL),
  ('Books', 12, NULL),
  ('Single Semi-Private Appointment', 6, NULL),
  ('Next Stop: Culver City! - 3 classes for $73', 1, NULL),
  ('Master Instructor - Single Private Session', 6, NULL),
  ('Classpass Special:  4 Classes for $75', 2, NULL),
  ('Master Instructor - Series of 20 Privates', 6, NULL),
  ('Series of 5 Semi-Private Appoinments', 6, NULL),
  ('Master Instructors - Series of 20 Privates', 6, NULL),
  ('Mighty Monthly  20 Pass', 1, NULL),
  ('Mighty Monthly 15 Classes', 1, NULL),
  ('Love Your Practice - 10 Privates', 6, NULL),
  ('Series of 40 Privates Appointments', 6, NULL),
  ('Series of 40 Private Appointments', 6, NULL),
  ('Staff Reformer Rental', 6, NULL),
  ('Next Stop: Danville! - 3 classes for $73', 1, NULL),
  ('Series of 10 Master Trainer Privates', 6, NULL),
  ('Ready Set Spring - 8 classes for $240 (WW/SM only, limit 3)', 6, NULL),
  ('Series of 20 Private Sessions', 6, NULL),
  ('Welcome Back: Private Client Special 3 for $225', 2, NULL),
  ('Single Master Trainer Private', 6, NULL),
  ('Series of 10 Semi Private Appointments', 6, NULL),
  ('20 Pack Live Stream Pilates Private', 6, NULL),
  ('Danville Founder’s 50 Mighty Monthly - First Month', 1, NULL),
  ('Love Your Practice - 10 Master Privates', 6, NULL),
  ('Series of 40 Private Pilates', 6, NULL),
  ('Classpass Special: 4 classes for $75', 2, NULL),
  ('Series of 5 Master Trainer Privates', 6, NULL),
  ('Master Instructor - 10 Sessions', 6, NULL),
  ('Single Semi Private Appointment', 6, NULL),
  ('Mighty Monthly 8 Private Pass', 1, NULL),
  ('MMP 20', 6, NULL),
  ('Staff Drop In Class - $5', 6, NULL),
  ('Mighty Pilates Workshops', 6, NULL),
  ('Danville Mini Mighty Monthly Pass', 1, NULL),
  ('Final Payment (Staff Discount) - PTT', NULL, 1),
  ('Private Room Rental', 6, NULL),
  ('New Client Duet Special 3 for $145', 2, NULL),
  ('Master Instructor - 10 Semi Privates', 6, NULL),
  ('Tinsel & Tone Flash Sale - 6 classes for $199 (Berkeley/Lafayette only)', 6, NULL),
  ('Classpass Special: 4 Classes for $75', 2, NULL),
  ('Marin Founders MMP', 1, NULL),
  ('Master Instructor - Single Semi Private', 6, NULL),
  ('Welcome Back Offer: 5 classes for $99 (Valid for 2 months)', 2, NULL),
  ('Next Stop: Santa Barbara! - 3 classes for $73', 1, NULL),
  ('Series of 5 Semi Private Appointments', 6, NULL),
  ('5  Mat Classes - At home', 6, NULL),
  ('1st Payment (Staff Discount) - PTT', NULL, 1),
  ('1st Payment (10% off) - PTT', NULL, 1),
  ('Final Payment (10% off) - PTT', NULL, 1),
  ('Series of 20 Master Trainer Privates', 6, NULL),
  ('Master Instructor - Series of 10 Semi-Privates', 6, NULL),
  ('Series of 10 Semi-Privates with Master Trainer', 6, NULL),
  ('Group Class Buyout - Private Class', 1, NULL),
  ('1-Time Special Offer:  4 Classes for $75', 2, NULL),
  ('Single Apprentice Session', 6, NULL),
  ('Master Instructor - Series of 5  Semi-Privates', 6, NULL),
  ('MMP Popup', 1, NULL),
  ('Specialty Class', 1, NULL),
  ('Series of 5 Semi-Private Appointments', 6, NULL),
  ('Master Instructor', 6, NULL),
  ('Group Class Buyout - Event', 1, NULL),
  ('Apprentice - Series of 5 Privates', 6, NULL),
  ('Mini Mighty Monthly (5 classes)', 1, NULL),
  ('Mighty Staff Private Rental', 1, NULL),
  ('Love Your Practice - 20 Master Privates', 6, NULL),
  ('Bloom In Strength Flash Sale - 8 classes of $280', 6, NULL),
  ('Staff Classes', 1, NULL),
  ('MMP Master 8 Private Pass', 1, NULL),
  ('Master Instructor - Single Semi-Private', 6, NULL),
  ('Master Instructor - Single Semi Private Session', 6, NULL),
  ('MMP Pop Up', 1, NULL),
  ('Non-MMP Member', 1, NULL),
  ('5 Mat Pilates - At home', 6, NULL),
  ('Final Payment', NULL, 1),
  ('PTT Books', NULL, 1),
  ('Work Hard Play Hard: 1 Room (Prime)', 6, NULL),
  ('1st  Payment (10% off) - PTT', NULL, 1),
  ('Private Class Buyout', NULL, 1),
  ('5 Mat Pilates - At Home', 6, NULL),
  ('Series of 5 Livestream Classes', 6, NULL),
  ('Donation Class', 1, NULL),
  ('Welcome Back Offer: 5 classes for $99 (2 months)', 2, NULL),
  ('1  Mat Class - At home', 6, NULL),
  ('MMP Pop UP', 1, NULL),
  ('Single Semi-Private with Master Trainer', 6, NULL),
  ('Mighty Workshop', 1, NULL),
  ('Series of 10 Trio Privates', 6, NULL),
  ('Non MMP client sign up', 1, NULL),
  ('Apprentice Session', 6, NULL),
  ('Mighty Staff Private Duo Rental', 6, NULL),
  ('Non-MMP Pop Up Sign Up', 1, NULL),
  ('Mighty Mixer: 1 Room (Prime)', 6, NULL),
  ('Single Livestream Class', 6, NULL),
  ('Non-Member', 6, NULL),
  ('Master Instructor - Series of 5 Semi-Privates', 6, NULL),
  ('Master Instructor - 5 Sessions', 6, NULL),
  ('PTT Make-up Workshop', NULL, 1),
  ('PTT Make-up workshop', NULL, 1),
  ('Mighty Mixer: 1 Room (Non Prime)', 1, NULL),
  ('Non-MMP Members', 1, NULL),
  ('Teacher Training Make Up', NULL, 1),
  ('Apprentice Duet', 6, NULL),
  ('8 Machine Classes', 1, NULL),
  ('Non-MMP Mmeber', 1, NULL),
  ('Series of 5 Semi-Privates with Master Trainer', 6, NULL),
  ('Master Instructor - 5 Semi Privates', 6, NULL),
  ('Apprentice Private 5 Pack', 6, NULL),
  ('Non-MMP Member Pop-Up', 1, NULL),
  ('6 Week Series-Man Up Pilates Build Strength', 6, NULL),
  ('Mighty Staff Duo Rental', 6, NULL),
  ('Early Bird Deposit', NULL, 1),
  ('Trio Private', 6, NULL),
  ('Trio Private Appointment', 6, NULL),
  ('Live Stream Pilates Private', 6, NULL),
  ('1 Mat Pilates - At Home Class', 6, NULL),
  ('Make Up Session - PTT', NULL, 1),
  ('6 Week Series', 6, NULL),
  ('Voyager Pass', NULL, 10),
  ('MMP Member Pop Up', NULL, 1),
  ('MMP member Pop Up', NULL, 1),
  ('MMP Workshop', NULL, 1),
  ('PTT Make Up', NULL, 1),
  ('Unlimited Livestream (PTT students only)', 1, NULL),
  ('New Client Special: 5 for $99 (valid for 1 month) Copy', 1, NULL),
  ('1 Mat Pilates - At home', 6, NULL),
  ('Private Rental Marin', 1, NULL),
  ('Pilates and Sound Bath', 1, NULL),
  ('Trio', 6, NULL),
  ('New Staff 10 machine classes', 6, NULL),
  ('Private Rental', 6, NULL),
  ('1 Mat Class - At home', 6, NULL),
  ('Yelp Google Review Class', 1, NULL),
  ('MMP Member Birthday Class', 1, NULL),
  ('Soul Cycle Marin Staff Classes', 1, NULL),
  ('MMP Members', 1, NULL),
  ('(Existing MMP only)  Unlimited Mat At Home Mat Classes', 1, NULL),
  ('Feedback Class', 1, NULL),
  ('Private Room Rental PTT', 6, NULL),
  ('Post Baby Strength & Pelvic Floor Connection (4 we', 6, NULL),
  ('MMP Pop-Up', 1, NULL),
  ('Gympass', NULL, 15),
  ('Friends On The Frontlines - 2 Weeks of FREE Pilates', 6, NULL),
  ('MMP Unlimited Mat Pilates - At Home', 1, NULL),
  ('Mighty Loyal Class', 1, NULL),
  ('MMP Guest Pass', 1, NULL);
