[theme]
base = "light"
primaryColor = "#F26722"
backgroundColor = "#f6f4ef"
secondaryBackgroundColor = "#ffffff"
textColor = "#241f19"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
