[theme]
base = "dark"
primaryColor = "#b5623f"
backgroundColor = "#211d16"
secondaryBackgroundColor = "#2a2620"
textColor = "#e6ddcc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
